// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalLibrary.Data;

#nullable disable

namespace PersonalLibrary.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260118015018_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalLibrary.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("PersonalLibrary.Models.BookReading", b =>
                {
                    b.Property<int>("BookReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookReadingId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFinished")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ReadingStatusId")
                        .HasColumnType("int");

                    b.HasKey("BookReadingId");

                    b.HasIndex("BookId");

                    b.HasIndex("ReadingStatusId");

                    b.ToTable("BookReadings");
                });

            modelBuilder.Entity("PersonalLibrary.Models.ReadingStatus", b =>
                {
                    b.Property<int>("ReadingStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReadingStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ReadingStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReadingStatuses");

                    b.HasData(
                        new
                        {
                            ReadingStatusId = 1,
                            Name = "TBR",
                            SortOrder = 1
                        },
                        new
                        {
                            ReadingStatusId = 2,
                            Name = "Reading",
                            SortOrder = 2
                        },
                        new
                        {
                            ReadingStatusId = 3,
                            Name = "Finished",
                            SortOrder = 3
                        },
                        new
                        {
                            ReadingStatusId = 4,
                            Name = "DNF",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("PersonalLibrary.Models.BookReading", b =>
                {
                    b.HasOne("PersonalLibrary.Models.Book", "Book")
                        .WithMany("BookReadings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalLibrary.Models.ReadingStatus", "ReadingStatus")
                        .WithMany("BookReadings")
                        .HasForeignKey("ReadingStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("ReadingStatus");
                });

            modelBuilder.Entity("PersonalLibrary.Models.Book", b =>
                {
                    b.Navigation("BookReadings");
                });

            modelBuilder.Entity("PersonalLibrary.Models.ReadingStatus", b =>
                {
                    b.Navigation("BookReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
